name: warp_env  
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  - pytorch=2.2
  - torchvision=0.20
  - torchaudio=2.5
  - pytorch-cuda=12.1 
  
  - timm  
  - scikit-learn  
  - pandas  
  - numpy  
  - matplotlib  
  - seaborn  
  - scipy
  
  - albumentations
  - pillow  
  
  - tqdm  
  - wandb  

  - pyyaml  
  - requests  
  - ipykernel  
  - jupyterlab  
  - psutil  
  - gdown 
  - ptflops 

  - pip:
      - torchsummary  
      - torchmetrics  
      - pytorch-lightning  
      - pycocotools
      - kornia
      - tensorboard 
      - opencv-python-headless
      - seaborn
      - captum
      - gpustat
      - nvitop
      - uv